### ISSUE TITLE
[Fix] Add new attributes to authn request schema validator

### ISSUE THREAD

**Issue by francescatronconi** [peppelinux/spid-cie-oidc-django#29]
Add this attributes to authn request schema validator both for spid and cie:
- sub
- iss
- iat
- exp
- jti
- aud

jti can be produced like this:
````
import uuid

jti: str(uuid.uuid4())
````

**Comment by peppelinux** [comment]
AgID confirmed that these are commons claims for every jwt and also required

**Comment by peppelinux** [comment]
Done here
https://github.com/peppelinux/spid-cie-oidc-django/blob/4609e8e949b93a537daa14a51f30bcb7951bd7a9/spid_cie_oidc/onboarding/schemas/authn_requests.py#L137
